language: elixir

dist: bionic

elixir:
  - 1.7
  - 1.8

otp_release:
  - 20.1
  - 20.3
  - 21.0
  - 21.3

sudo: false

notifications:
  irc:
    channels:
      - "chat.freenode.net#runas"
    on_success: change
    on_failure: always
    use_notice: true

email: false

script:
  - mix compile
  - mix test
  - mix test test/**/*.exs
  - MIX_ENV=dev mix dialyzer --halt-exit-status

cache:
  directories:
    - priv/plts
